kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: milvus-operator-role
rules:
  - verbs:
      - 'get'
      - 'list'
      - 'watch'
      - 'create'
    apiGroups:
      - "security.openshift.io"
    resources:
      - 'securitycontextconstraints'