kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: milvus-operator-rb
subjects:
  - kind: ServiceAccount
    name: milvus-operator
    namespace: milvus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: milvus-operator-role