apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./components/openshift-cert-manager/operator
    targetRevision: HEAD
    repoURL: https://github.com/Nordic-MVP-GitOps-Repos/milvus-openshift
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
