apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: milvus-cluster
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./components/milvus/base
    targetRevision: HEAD
    repoURL: https://github.com/Nordic-MVP-GitOps-Repos/milvus-openshift
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
