apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  namespace: milvus-operator
  name: my-release
spec:
  mode: cluster
  #config:
  #  common:
  #    security:
  #      tlsMode: 1
  #  tls:
  #    caPemPath: configs/cert/ca.pem
  #    serverKeyPath: configs/cert/server.key
  #    serverPemPath: configs/cert/server.pem
